// AppNotification.swift
// Algo
//
// Data models for the notifications system.
// Maps to GET /notifications response from the Algo backend.

import Foundation

// MARK: - AppNotification

/// Represents a single notification delivered to the user.
/// Notifications are generated by the backend alert engine and
/// delivered via push notifications or in-app polling.
struct AppNotification: Codable, Identifiable, Sendable {

    /// Unique notification identifier (e.g., "notif_001").
    let id: String

    /// Notification category type.
    /// Possible values: "hot_lead", "campaign_drop", "budget_alert",
    /// "revenue_spike", "credit_low", "followup_overdue".
    let type: String

    /// Short title for the notification.
    let title: String

    /// Detailed notification body text.
    let body: String

    /// Severity level: "high", "medium", or "low".
    let severity: String

    /// Whether the user has read this notification.
    let read: Bool

    /// Optional deep link URL for navigating to related content.
    let actionUrl: String?

    /// ISO 8601 timestamp when the notification was created.
    let createdAt: String
}

// MARK: - CodingKeys

extension AppNotification {

    enum CodingKeys: String, CodingKey {
        case id
        case type
        case title
        case body
        case severity
        case read
        case actionUrl = "action_url"
        case createdAt = "created_at"
    }
}

// MARK: - NotificationListResponse

/// Paginated response from the `/notifications` endpoint.
struct NotificationListResponse: Codable, Sendable {

    /// Array of notification items for the current page.
    let notifications: [AppNotification]

    /// Total count of unread notifications across all pages.
    let unreadCount: Int
}

extension NotificationListResponse {

    enum CodingKeys: String, CodingKey {
        case notifications
        case unreadCount = "unread_count"
    }
}

// MARK: - Notification Type Helpers

extension AppNotification {

    /// SF Symbol name appropriate for this notification type.
    var iconName: String {
        switch type {
        case "hot_lead":
            return "flame.fill"
        case "campaign_drop":
            return "chart.line.downtrend.xyaxis"
        case "budget_alert":
            return "dollarsign.circle.fill"
        case "revenue_spike":
            return "arrow.up.right.circle.fill"
        case "credit_low":
            return "creditcard.fill"
        case "followup_overdue":
            return "clock.badge.exclamationmark.fill"
        default:
            return "bell.fill"
        }
    }

    /// Human-readable label for the notification type.
    var typeLabel: String {
        switch type {
        case "hot_lead":         return "Hot Lead"
        case "campaign_drop":    return "Campaign Drop"
        case "budget_alert":     return "Budget Alert"
        case "revenue_spike":    return "Revenue Spike"
        case "credit_low":       return "Low Credits"
        case "followup_overdue": return "Overdue Follow-up"
        default:                 return "Notification"
        }
    }
}
