// Alert.swift
// Algo
//
// Alert model matching the backend alert schema.
// Used in dashboard alerts and notification routing.

import Foundation

// MARK: - AlertItem

/// Represents a proactive alert generated by the backend alert engine.
/// Alerts notify users of important events like hot leads, campaign drops, etc.
struct AlertItem: Codable, Identifiable, Sendable {

    /// Unique alert identifier (e.g., "alt_001").
    let id: String

    /// Alert category type.
    /// Possible values: "hot_lead", "campaign_drop", "budget_alert",
    /// "revenue_spike", "credit_low", "followup_overdue".
    let type: String

    /// Severity level determining visual treatment.
    /// Possible values: "high", "medium", "low".
    let severity: String

    /// Short descriptive title for the alert.
    let title: String

    /// Detailed message explaining the alert condition.
    let message: String

    /// ISO 8601 timestamp when the alert was created.
    let createdAt: String

    /// Optional action that can be taken in response to the alert.
    let action: AlertAction?
}

// MARK: - AlertAction

/// Describes an action that can be taken in response to an alert.
/// For example, viewing a specific lead or navigating to a campaign.
struct AlertAction: Codable, Sendable {

    /// The action type identifier (e.g., "VIEW_LEAD", "VIEW_CAMPAIGN").
    let type: String

    /// Optional parameters for the action (e.g., `["lead_id": "lead_sarah_001"]`).
    let params: [String: String]?
}

// MARK: - CodingKeys

extension AlertItem {

    enum CodingKeys: String, CodingKey {
        case id
        case type
        case severity
        case title
        case message
        case createdAt = "created_at"
        case action
    }
}

// MARK: - Alert Type Helpers

extension AlertItem {

    /// SF Symbol name appropriate for this alert type.
    var iconName: String {
        switch type {
        case "hot_lead":
            return "flame.fill"
        case "campaign_drop":
            return "chart.line.downtrend.xyaxis"
        case "budget_alert":
            return "dollarsign.circle.fill"
        case "revenue_spike":
            return "arrow.up.right.circle.fill"
        case "credit_low":
            return "creditcard.fill"
        case "followup_overdue":
            return "clock.badge.exclamationmark.fill"
        default:
            return "bell.fill"
        }
    }

    /// Human-readable label for the alert type.
    var typeLabel: String {
        switch type {
        case "hot_lead":         return "Hot Lead"
        case "campaign_drop":    return "Campaign Drop"
        case "budget_alert":     return "Budget Alert"
        case "revenue_spike":    return "Revenue Spike"
        case "credit_low":       return "Low Credits"
        case "followup_overdue": return "Overdue Follow-up"
        default:                 return "Alert"
        }
    }
}
